markhor:
  position_controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      front_left_flipper_joint:
        type: position_controller/JointPositionController
        joint: 'front_left_flipper_joint'
        pid: {p: 10.0, i: 0.0, d: 1.0}
      front_right_flipper_joint:
        type: position_controller/JointPositionController
        joint: 'front_right_flipper_joint'
        pid: {p: 10.0, i: 0.0, d: 1.0}
      rear_left_flipper_joint:
        type: position_controller/JointPositionController
        joint: 'rear_left_flipper_joint'
        pid: {p: 10.0, i: 0.0, d: 1.0}
      rear_right_flipper_joint:
        type: position_controller/JointPositionController
        joint: 'rear_right_flipper_joint'
        pid: {p: 10.0, i: 0.0, d: 1.0}
  velocity_controller:
    type: "diff_drive_controller/DriffDriveController"
    left_wheel : 'left_track_joint'
    right_wheel : 'right_track_joint'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]