joint_limits:
  front_left_flipper_joint:
    has_position_limits: true
    min_position: -1.5708
    max_position: 1.5708
  front_right_flipper_joint:
    has_position_limits: true
    min_position: -1.5708
    max_position: 1.5708
  rear_left_flipper_joint:
    has_position_limits: true
    min_position: -1.5708
    max_position: 1.5708
  rear_right_flipper_joint:
    has_position_limits: true
    min_position: -1.5708
    max_position: 1.5708