markhor:
  hardware_interface:
    joints:
      - front_left_flipper_joint
      - front_right_flipper_joint
      - rear_left_flipper_joint
      - rear_right_flipper_joint
      - left_track_joint
      - right_track_joint